// scripts/refresh-topics.mjs — compute SciVal topic clusters locally and push
// them to the live site's KV cache.
//
// Why: the SciVal API entitlement is IP-based, so it works from the university
// network but 403s from Vercel's servers. Run this from an entitled network
// (campus or VPN) whenever you want to refresh the What We Do page:
//
//   node scripts/refresh-topics.mjs
//
// Reads SCOPUS_API_KEY and SETTINGS_PASSWORD from .env.

import { readFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
for (const line of readFileSync(join(root, ".env"), "utf8").split("\n")) {
  const m = line.match(/^([A-Z_]+)=(.*)$/);
  if (m && !process.env[m[1]]) process.env[m[1]] = m[2];
}

const { computeTopics } = await import(join(root, "api/topics.js"));
const { computeImpact } = await import(join(root, "api/altmetric.js"));
const { UNIVERSITIES }  = await import(join(root, "src/data.js"));
const { writeFileSync } = await import("fs");

const SITE = process.env.SITE_URL || "https://iuca-pages.vercel.app";

console.log(`Computing topic areas for ${UNIVERSITIES.length} universities…`);
const debug = [];
const areas = await computeTopics(UNIVERSITIES, process.env.SCOPUS_API_KEY, debug);
debug.forEach(d => console.log("  !", d));
console.log(`Got ${areas.length} areas:`);
areas.forEach(a => console.log(`  - ${a.name} — ${a.paperCount} papers, ${a.uniCount} unis, ${a.clusterCount} clusters`));

if (!areas.length) {
  console.error("No areas computed — are you on a SciVal-entitled network?");
  process.exit(1);
}

// 1. Write the committed topics snapshot — served by /api/topics when KV is absent.
const now = new Date().toISOString();
const snapshot = { areas, updatedAt: now, cachedAt: now };
writeFileSync(join(root, "src/topics-snapshot.js"),
  `// Generated by scripts/refresh-topics.mjs — do not edit by hand.\n` +
  `export const TOPICS_SNAPSHOT = ${JSON.stringify(snapshot, null, 1)};\n`);
console.log("Wrote src/topics-snapshot.js — commit and push to update the site.");

// 1b. Compute + write the Impact (Altmetric) snapshot — served by /api/altmetric.
try {
  console.log("\nComputing Impact papers (Altmetric + SciVal)…");
  const papers = await computeImpact({ months: 6, limit: 10 });
  const withArea = papers.filter(p => p.areaId).length;
  console.log(`Got ${papers.length} impact papers (${withArea} area-tagged):`);
  papers.slice(0, 5).forEach(p => console.log(`  - [${p.score}] ${p.areaName || "—"}: ${p.title.slice(0, 55)}`));
  if (papers.length) {
    writeFileSync(join(root, "src/impact-snapshot.js"),
      `// Generated by scripts/refresh-topics.mjs — do not edit by hand.\n` +
      `export const IMPACT_SNAPSHOT = ${JSON.stringify({ papers, total: papers.length, fetchedAt: now }, null, 1)};\n`);
    console.log("Wrote src/impact-snapshot.js.");
  } else {
    console.warn("No impact papers computed — leaving existing snapshot in place.");
  }
} catch (err) {
  console.warn("Impact compute failed (leaving existing snapshot):", err.message);
}

// 2. Also push to KV via the live endpoint (instant update, no deploy needed)
try {
  const r = await fetch(`${SITE}/api/save-topics`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ password: process.env.SETTINGS_PASSWORD, areas }),
  });
  const body = await r.json();
  if (r.ok) console.log(`Also saved to KV on ${SITE} — live immediately.`);
  else console.warn("KV save skipped:", body.error);
} catch (err) {
  console.warn("KV save skipped:", err.message);
}
